# Include pywal colors
include ~/.cache/wal/colors-kitty.conf

# Set opacity
background_opacity 0.8

map f1 launch --type=tab --cwd=current


# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
